# Generated by Django 5.2.1 on 2025-05-31 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_is_on_vacation'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='career_start_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
